---
title: "Just a manhattan plot"
author: "Nick Strayer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

## Load Phewas Results

```{r load_data}
library(tidyverse)
library(meToolkit)
# Run install_github("tbilab/meToolkit") to make sure you have the latest version

phewas_results <- read_csv(here::here('inst/demo_app/data/phewas_results.csv'))

# Add category colors to data
cat_colors <- phewasHelper::category_colors()
phewas_results$color <- cat_colors[phewas_results$category]

phewas_results %>% 
  head() %>% 
  knitr::kable()
```


## Showing Manhattan Plot

```{r manhattan_plot}
# Decide cutoff that declares what codes are initially selected
significance_cutoff <- 0.01

selected_codes <- phewas_results %>%
  dplyr::filter(p_val < significance_cutoff) %>%
  dplyr::pull(code)

r2d3::r2d3(
  data = phewas_results,
  script = system.file("d3/manhattan_plot/manhattan_plot.js", package = "meToolkit"),
  container = 'div',
  dependencies = c(
    "d3-jetpack",
    system.file("d3/helpers.js", package = "meToolkit"),
    system.file("d3/manhattan_plot/phewas_table.js", package = "meToolkit"),
    system.file("d3/manhattan_plot/clusterize.js", package = "meToolkit")
  ),
  css = c(
    system.file("d3/helpers.css", package = "meToolkit"),
    system.file("d3/manhattan_plot/manhattan_plot.css", package = "meToolkit"),
    system.file("css/common.css", package = "meToolkit")
  ),
  height = "100vh",
  width = "100%",
  options = list(
    msg_loc = "standalone",
    selected = selected_codes,
    sig_bar_locs = significance_cutoff,
    colors = list(
      light_grey = "#f7f7f7",
      med_grey   = "#d9d9d9",
      light_blue = "#4292c6",
      green      = "#74c476"
    )
  )
)
```
