#' Interactive individual-level data network diagram of patients to codes
#'
#' @param id Unique id of module
#' @param height How tall we want this module to be in css units (defaults to '500px')
#'
#' @return HTML tag containing interactive network
#' @export
#'
#' @examples
#'
#' network2d_UI('mycomorbidityNetwork2d', '100%')
network2d_UI <- function(id, height = '500px') {
  ns <- NS(id)
  tagList(
    r2d3::d3Output(ns("plot"), height = height)
  )
}
#' Server function of snp info panel
#'
#' @param input,output,session Auto-filled by callModule | ignore
#' @param network_data Individual network data as generated by \code{meToolkit::makeNetworkData}
#' @param snp_filter boolean containing info on if we've filtered by snp or not.
#' @return
#' @export
#'
#' @examples
#' callModule(info_panel, 'info_panel', snp_name, individual_data, subset_maf)
network2d <- function(input, output, session, network_data, snp_filter) {
  # send data and options to the 2d plot
  output$plot <- r2d3::renderD3({
    r2d3::r2d3(
      data = jsonlite::toJSON(network_data),
      script = here('inst/d3/comorbidityNetwork2d/index.js'),
      container = 'div',
      dependencies = "d3-jetpack",
      options = list(
        just_snp = snp_filter,
        msg_loc = session$ns('message')
      )
    )
  })

  filtering_action <- reactive({
    validate(need(input$message, message = FALSE))
    input$message
  })

  return(filtering_action)
}
